Updated feedstock to version 0.6.1
conda-forge/nb2plots-feedstock pull request #2
Opened 2022-07-24 04:36 UTC by theXYZT

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2022-07-24 04:36 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found some lint.

Here's what I've got...


For **recipe**:

 * noarch: python recipes are required to have a lower bound on the python version. Typically this means putting `python >=3.6` in **both** `host` and `run` but you should check upstream for the package's Python compatibility.

2022-07-24 04:39 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found some lint.

Here's what I've got...


For **recipe**:

 * ``requirements: host: python>=3.7`` must contain a space between the name and the pin, i.e. ``python >=3.7``
 * ``requirements: run: python>=3.7`` must contain a space between the name and the pin, i.e. ``python >=3.7``
 * noarch: python recipes are required to have a lower bound on the python version. Typically this means putting `python >=3.6` in **both** `host` and `run` but you should check upstream for the package's Python compatibility.

2022-07-24 04:40 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2022-07-24 04:40 UTC, theXYZT commented
@conda-forge-admin, please rerender

2022-07-27 15:30 UTC, theXYZT commented
@CurtLH Is there anything I am missing?

2022-07-31 21:25 UTC, theXYZT commented
@conda-forge/staged-recipes Would like to merge this if possible but haven't received a review or feedback.

2022-07-31 21:30 UTC, theXYZT commented
@conda-forge-admin, please ping team

2022-07-31 21:30 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-webservice.

I was asked to ping @conda-forge/nb2plots and so here I am doing that.

2022-08-02 06:50 UTC, theXYZT commented
@conda-forge-admin, please add user @theXYZT

2022-10-04 13:55 UTC, zklaus requested changes
We prefer to base builds on releases on Pypi rather than github tags. Since the new version is available on Pypi, could you please revert the changes in lines 1-10 that switch to the github tag? You can then also add your github username to the list of maintainers at the bottom.

2022-10-04 14:16 UTC, theXYZT commented
@zklaus I can't figure out how to do that. On PyPi (https://pypi.org/project/nb2plots/#files), the only release file is a wheel. I can't find a link to a tarball.

2022-10-04 15:00 UTC, zklaus commented
Sorry, @theXYZT, I think you are right. What an odd choice. I would suggest to raise the issue upstream so that source archives will be put on Pypi in the future, but you are right to move to the tags here, I guess.

I would suggest keeping the jinja2 variable (i.e. the old line 1) and hoping that upstream follows through in putting source releases out again.

2022-10-04 19:54 UTC, theXYZT commented
@zklaus Done! Is this good enough to call this PR done?

2022-10-05 08:37 UTC, zklaus approved these changes
I think it's ok. I left one small suggestion for the download and I still suggest that you add yourself to the list of maintainers here, i.e. simply add a line add the bottom with
```yaml
    - theXYZT
```

2022-10-05 08:37 UTC, zklaus commented on recipe/meta.yaml
> +  url: https://github.com/matthew-brett/nb2plots/archive/refs/tags/{{ version }}.tar.gz
```suggestion
  # As of 0.6.1, upstream puts only wheels on Pypi, hence we take the source directly from github.
  url: https://github.com/matthew-brett/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
```

2022-10-07 17:51 UTC, theXYZT commented
@zklaus Done! Hope that's good enough.

2022-10-10 12:57 UTC, zklaus commented
@conda-forge/core, could somebody have a look here? The maintainer seems unresponsive (no reply after 3 months) and @theXYZT is willing to step up and help out.

2022-10-10 12:58 UTC, merged

2022-10-10 13:02 UTC, zklaus commented
Thanks, @xhochy!